### PR TITLE
Adding Kate in IDE (also see comments regarding the github workflow)

### PR DESCRIPTION
**Pull request by uncomfyhalomacro**
Also added Fisher's work for the github workflows.

### CODE REVIEW

**Comment by uncomfyhalomacro** [comment]
@fisher60 i guess it is because one or more lines really are too long inside `answers.py`. i auto-formatted it with `black`.

**Comment by vivax3794** [comment]
since you are adding the pyproject.toml file it might be nice to just fill it out completely, I made this one when I was planning to pr in poetry.
```toml
name = "bestpy"
version = "0.0.1"
description = "A module to prove your friends (or adversaries) wrong."
authors = ["Gustav Odinger"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/gustavwilliam/bestpy"
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
]
```

**Comment by uncomfyhalomacro** [comment]
Hello @vivax3794. Thanks! I have filled out using what you made. Any more suggestions or changes you might want to add? Btw I am new to this stuff
```
[tool.poetry]
name = "bestpy"
version = "0.0.1"
description = "A module to prove your friends (or adversaries) wrong."
authors = ["Gustav Odinger"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/gustavwilliam/bestpy"
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
pre-commit = "^2.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by vivax3794** [comment]
I mainly just added in what was in the setup.py file (which can actually be deleted now that poetry is setup), here are the [docs](https://python-poetry.org/docs/pyproject/) for all the attributes that can go in the file if you see any more you would want to add.

**Comment by gustavwilliam** [comment]
@ReneganRonin Is this some kind of compound PR? There is already a PR from Fisher for adding Poetry, I believe. Is this adding the same thing, plus one extra name to the IDEs category?

**Comment by uncomfyhalomacro** [comment]
@gustavwilliam hello vester. yeah my bad for this pr. i do think it is best to close this and i will create a new branch to separate them and pull fisher's features/ci branch to fix the linting. then i will pr to the branch @fisher60 made instead once the linting errors are fixed. i wont pr to main.

**Comment by gustavwilliam** [comment]
Sounds perfect.

**Pull request closed without merging**
